services:
    sveltekit:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - valkey
        environment:
            DATABASE_URL: redis://valkey:6379
        restart: unless-stopped

    valkey:
        image: valkey/valkey:7.2.6-alpine
        volumes:
            - valkey_data:/var/lib/valkey
        ports:
            - "6379:6379"
        restart: unless-stopped

volumes:
    valkey_data:
