name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PUBLIC_PAYPAL_LINK: _
  PUBLIC_IMPRINT_EMAIL_ADDRESS: _
  PUBLIC_IMPRINT_STREET: _
  PUBLIC_IMPRINT_TOWN: _
  PUBLIC_PHONE_NUMBER: _
  PUBLIC_UMAMI_SCRIPT: _

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
