name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Test build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create environment variables
              run: cp .env.example .env

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

    format:
        name: Test formatting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Format check
              run: npm run format

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Linter check
              run: npm run lint

    svelte-check:
        name: Run svelte-check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Svelte check
              run: npm run check
