name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create environment variables
              run: cp .env.example .env

            - name: Fetch line names
              run: chmod +x scripts/line-shapes.sh && ./scripts/line-shapes.sh

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

    format:
        name: Formatting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Format check
              run: npm run format

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Linter check
              run: npm run lint

    svelte-check:
        name: Svelte-check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create environment variables
              run: cp .env.example .env

            - name: Fetch line names
              run: chmod +x scripts/line-shapes.sh && ./scripts/line-shapes.sh

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Svelte check
              run: npm run check

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create environment variables
              run: cp .env.example .env

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test

    lockfile:
        name: Lockfile
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Copy current lockfile
              run: cp package-lock.json initial-package-lock.json

            - name: Re-generate lockfile
              run: npm install --package-lock-only

            - name: Compare lockfiles
              run: diff initial-package-lock.json package-lock.json
